version: "3.8"

services: 
    angular-ui:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - target: 4200
              published: 4200
              protocol: tcp
              mode: host
        volumes:
            - .:/app
        command: ng serve --host 0.0.0.0 --disableHostCheck --poll=2000
